name: current_location
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.2
  dio: ^5.3.3
  get: ^4.6.6
  cached_network_image: ^3.3.0
  mocktail: ^1.0.1
  collection: ^1.17.2
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  url_launcher: ^6.2.1
  geolocator: ^10.1.0
  connectivity_plus: ^5.0.1
  flutter_map_cache: ^1.3.1
  dio_cache_interceptor_file_store: ^1.2.2
  path_provider: ^2.1.1
  dio_cache_interceptor: ^3.4.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
